### ISSUE TITLE
Elasticsearch connector does not authenticate

### ISSUE THREAD

**Issue by andremacola** [swirlai/swirl-search#1028]
When Elastic need to authenticate to query, the credentials is not passed the right way to the server: ("user", "pass")

`xxx.xxx.xxx.xxx - ( [06/Dec/2023:19:10:28 -0300] "POST /xxxxx/_search HTTP/1.1" 401 495 "-" "elasticsearch-py/8.10.1 (Python/3.11.5; elastic-transport/8.10.0)"`

Swirl is sending a `(` instead of  user.

**Comment by erikspears** [comment]
Hi @andremacola ,

Thanks for bringing this to our attention.  We'll take a look.

May I ask which verison of Elastic you're using?  And are you seeing it on a local or cloud Elastic?

Thanks,
--Erik

**Comment by sid-swirl** [comment]
Hi @andremacola sorry for the delay in getting back to you. For elastic, the credentials need to be wrapped in parens, like this:

`"credentials": "(\"elastic\", \"elastic-password\")",`

If no auth is required, set credentials blank (""). Please, ping me if this continues.

**Comment by sid-swirl** [comment]
Hi, this is

**Comment by sid-swirl** [comment]
Hi - this is confirmed as a bug, I am fixing it now...

**Comment by sid-swirl** [comment]
This should address it, but won't be merged until tested. 
https://github.com/swirlai/swirl-search/issues/1028

If you want to try it, pull branch 'fixelastic' :-)

**Comment by andremacola** [comment]
Sorry for late response.
Elastic `8.11.3`
Self Hosted Elastic

**Comment by erikspears** [comment]
Hi @andremacola , thanks for that information!  The team is looking deeper into potential issues around auth with elastic (and opensearch).  We hope to address this in our next release.

Thanks,
--Erik

**Comment by erikspears** [comment]
Hello again,
This issue has been addressed and the updates will be part of our next release.  Should you wish to test drive the updates early, you can pull (or clone) our `develop` branch.  If you are updating to `develop` from a previous local intall of the main branch code, you will need to do a Database Migration, as outlined here in the docs:  https://docs.swirl.today/Admin-Guide.html#database-migration

Let us know if you have any questions about the process.
Thanks,
--Erik

**Comment by erikspears** [comment]
This issue was fixed in the Swirl 3.2.0, which has now been released.  Please note the slight change to the default configuration of the Elastic and OpenSearch SearchProviders.  Any exiting versions of those SPs would need to be updated accordingly.  Closing this out.
