### ISSUE TITLE
where is the front-end source code

### ISSUE THREAD

**Issue by HycJack** [swirlai/swirl-search#1086]
Hi, I want to customize the Galaxy UI, but I have not found the source code for the frontend. Can you please provide the frontend source code?

**Comment by erikspears** [comment]
Hi @HycJack ,

The Galaxy UI code has grown up in a different neighborhood, so to speak.  :) 

It lives in this BitBucket repo:  https://bitbucket.org/swirl-spyglass/spyglass/src/master/

We would welcome PRs to that code (`develop` branch, please), if you'd like to contribute!  If so, please provide us with your BitBucket username (you'll have to make an account there if you don't have one yet), and we'll add you to the project.

Many thanks,
--Erik

**Comment by erikspears** [comment]
Closing this Issue out.
