### ISSUE TITLE
AI Summary: No data

### ISSUE THREAD

**Issue by metabyte** [swirlai/swirl-search#1141]
**Describe the bug**
When I search on keywords and select a few answers/links, then toggle checkbox "Generate AI Response", the summary shows "no data". 
Looking at the logs, here is what I have:

`2024-01-31 19:48:37     Answer this query 'who is the best NBA player' given the following recent search results as background information. Do not mention that you are using the provided background information. Please cite the sources at the end of your response. Ignore information that is off-topic or obviously conflicting, without warning about it.
2024-01-31 19:48:37 2024-01-31 19:48:37,144 ERROR    error : 'ascii' codec can't encode character '\u2018' in position 7: ordinal not in range(128) while creating CGPT response` 

**Screenshots**
![image](https://github.com/swirlai/swirl-search/assets/5055793/b465d5eb-3860-48f2-9be0-9c07b78693fd)

**Swirl :**
 - Version: 3.0
 - Local or Docker: Docker
 - Desktop OS: MacOS Sonoma 14.2.1

**Comment by sid-swirl** [comment]
I can confirm this is an issue in 3.2, working on it now

**Comment by sid-swirl** [comment]
The issue only occurs when running with Docker. Local installation works fine. We're still working on it, will post again in the AM, sorry for the issue...

**Comment by metabyte** [comment]
Hi @erikspears , I can do that. But before getting further, the docker-compose.yml file in the quick start guide still show version '3' and not '3.2'. Is this normal?

**Comment by erikspears** [comment]
Hi @metabyte , oh I see what you mean...yes, that's fine.  For this experiment, we just want you to get ahold of the latest file.  I will make sure that .yml gets an update as well, that's a great catch, thank you!

And yes, if you're docker container log show 3.1.0, please do the fresh reinstall.  Many thanks!

**Comment by metabyte** [comment]
Udpate: just gone through a complete fresh install on Docker, with the latest __S_W_I_R_L__3_._2_._0. It is looking better since I managed to connect OpenAI, but as I don't have access to GPT-4 and only GPT-3, I get an error: `rror : Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}} while creating CGPT response` 
Where should I change to model 3.5-turbo?

**Comment by metabyte** [comment]
I figured the change in the settings.py, restarted and now I am getting the AI summary displayed. I think you can close this issue. 
![image](https://github.com/swirlai/swirl-search/assets/5055793/f59edea9-ae40-435c-b57d-60107f01cb8f)

**Comment by erikspears** [comment]
Hi @metabyte ,  great news!  Thanks for sticking with us through this process.  I'm glad you found the `settings.py` entries that you needed regarding the OpenAI model and were able to change those in. your Docker container.  We do indeed have gpt-4 as our default, and that can be changed to 3.5 turbo, as you did.

It's great to see your results too, thanks for sharing that screen grab!  Please let us know if you have any other questions.  We also have free Community Slack instance where we offer support ... feel free to jump in and raise questions there as well:
https://join.slack.com/t/swirlmetasearch/shared_invite/zt-1qk7q02eo-kpqFAbiZJGOdqgYVvR1sfw

Thanks again!
