### ISSUE TITLE
Hit highlighting: SWIRL adds a space before matching terms next to a comma

### ISSUE THREAD

**Issue by erikspears** [swirlai/swirl-search#119]
This behavior is most commonly seen in the Body field (see the example below), but I no reason it couldn't exist also in Title.  The gist is that when we highlight a matching terms that is next to a comma, we insert an extra space before the comma.  We have already completed the query and ranked the results, so the core function of the product is not an issue.  However, our hit highlighting code might need some tightening up soon.  See also Issue #77 

Running this query with the 3 default Google PSE SearchProviders active:  `q=strategic technology consulting`

On the 2nd page of results, there are few examples of this issue, see below.  I have checked some of the original pages, and there is no space before the comma in each case.

Example, result 16:
![Issue 119 - result 16 body](https://user-images.githubusercontent.com/98238295/220658992-4001e83c-f06e-487b-b713-04b62bfc0804.png)

Example, result 18:
![Issue 119 - result 18 body](https://user-images.githubusercontent.com/98238295/220659058-a3d0bf3e-c504-487f-8b7b-ee7fa17b1336.png)

Example, result 20:
![Issue 119 - result 20 body](https://user-images.githubusercontent.com/98238295/220659146-a7c5c259-8b33-4a5b-b4ba-95a97e33bb56.png)

**Comment by sidprobstein** [comment]
On deck for 1.10

**Comment by erikspears** [comment]
This case has been improved for the upcoming release (post 1.10.x).  We'll close it out when that release drops

**Comment by erikspears** [comment]
Fixed in 2.0
