### ISSUE TITLE
Review parsing of credentials and tokens everywhere

### ISSUE THREAD

**Issue by erikspears** [swirlai/swirl-search#159]
Found an issue with the parsing of Bearer tokens while working on a new SearchProvider that uses them.  The token I was testing with happened to have an equal sign `(=)` within the token itself, and that is also the character we currently split on when parsing Bearer token credentials in `requestsget.py` (line 156).  The syntax for the `credentials` line of a SearchProvider that uses a Bearer token looks like:
```
"credentials": "bearer=<your-token-here>
```

Spoke with @sid-swirl, and he's going to remedy this use-case as well as review parsing of all tokens throughout as there may be other places this could come into play (e.g. potentially with a BigQuery token, etc.).

**Comment by sidprobstein** [comment]
Fix for RequestsGet checked in to 1.10.1

**Comment by sidprobstein** [comment]
Fix for RequestsGet checked in to fix-cred-parse-159 branch (off main)

**Comment by sidprobstein** [comment]
https://github.com/swirlai/swirl-search/pull/160

**Comment by erikspears** [comment]
Fix merged to both `main` and the `1.10` branch (our forthcoming release).  Validated in main already, great stuff, @sid-swirl , thank you!
