### ISSUE TITLE
Connector: Asana

### ISSUE THREAD

**Issue by sid-swirl** [swirlai/swirl-search#687]
Asana is a web and mobile application that "makes it easier for your team to do more work that matters" - specifically, it helps organize, track, and manage work. Asana combines elements of project management, task tracking, and collaboration tools. 

Asana has a well formed API documented here: https://developers.asana.com/reference/rest-api-reference

A straightforward first step might be to build a SearchProvider that targets Asana tasks. This would use the gettasks API call as noted here: https://developers.asana.com/reference/gettasks

A good starting point would be the Atlassian SearchProvider for Issues which is here: https://github.com/swirlai/swirl-search/blob/main/SearchProviders/atlassian.json

**Comment by LunarMarathon** [comment]
Hi, I would like to work on this, please assign this to me. I'll go through the provided documentation but if there are any examples that I can refer to please let me know. Thank you!

**Comment by srbhr** [comment]
@LunarMarathon, thanks for taking up the issue. Feel free to join our [Slack ](https://join.slack.com/t/swirlmetasearch/shared_invite/zt-1qk7q02eo-kpqFAbiZJGOdqgYVvR1sfw)and ask the team about any issues you're facing.

**Comment by Yash-sudo-web** [comment]
is this issue resolved or can i be assigned and work on it?

**Comment by erikspears** [comment]
Closing this out.  We'll be shipping an Asana SP with Swirl 3.1.0.
