### ISSUE TITLE
Connector: Algolia

### ISSUE THREAD

**Issue by sid-swirl** [swirlai/swirl-search#688]
Algolia is a cloud-based search engine that provides businesses with search experiences. It enables websites and applications to quickly implement and optimize search functionalities, ensuring users can easily find and access information within the app.

API documentation for Algolia is here: https://www.algolia.com/doc/rest-api/search/

A good starting point would be a basic search. It appears Algolia supports both HTTP GET and POST for querying: https://www.algolia.com/doc/rest-api/search/#search-endpoints

It might be that a full Connector is not required, only a SearchProvider configuring the RequestsGet or RequestsPost connector.

**Comment by AbhiPatel10** [comment]
@sid-swirl I would like to work on this issue.

**Comment by Yash-sudo-web** [comment]
@sid-swirl can i work on this issue?

**Comment by sid-swirl** [comment]
Completed! Thank you!
