### ISSUE TITLE
Connector: Trello

### ISSUE THREAD

**Issue by sid-swirl** [swirlai/swirl-search#690]
Trello is a visual collaboration tool that creates a shared perspective for teams to organize, prioritize, and manage projects through customizable boards, lists, and cards. Inspired by the kanban system, Trello facilitates task tracking and project management with its drag-and-drop interface, allowing users to easily move tasks (cards) through different stages, assign responsibilities, set deadlines, and attach files. It is part of Atlassian now.

Trello does have APIs: https://developer.atlassian.com/cloud/trello/rest/api-group-actions/#api-group-actions

The search API is here: https://developer.atlassian.com/cloud/trello/rest/api-group-search/#api-group-search 

This looks like a typical REST API that returns JSON, so it may be easy to make a SearchProvider that configures RequestsGet to search Trello content. Look at the Atlassian connectors as a starting point: https://github.com/swirlai/swirl-search/blob/main/SearchProviders/atlassian.json

**Comment by neelshah2409** [comment]
I would like to work on it @sid-swirl

**Comment by srbhr** [comment]
@neelshah2409, thanks for taking up the issue. You've been assigned this issue. Feel free to join our [Slack ](https://join.slack.com/t/swirlmetasearch/shared_invite/zt-1qk7q02eo-kpqFAbiZJGOdqgYVvR1sfw) and ask the team about any issues you're facing.

**Comment by HarshMN2345** [comment]
i would to like to work on this @sid-swirl

**Comment by VrajPatelGitHub** [comment]
@sid-swirl I would also like to work on this issue please assign these to me.

**Comment by sidprobstein** [comment]
Accepted PR!
