### ISSUE TITLE
Connector: Vespa

### ISSUE THREAD

**Issue by sid-swirl** [swirlai/swirl-search#692]
Vespa.ai is a big data serving engine that allows you to apply AI to your data online, at any scale, with great performance. It is an open-source platform that provides a fully-featured search engine and vector database. It supports vector search (ANN), lexical search, and search in structured data, all in the same query. Integrated machine-learned model inference allows you to apply AI to make sense of your data in real-time to solve problems such as structured, text, and vector search, and real-time recommendation, personalization, and targeting. 

Documentation is here: https://docs.vespa.ai/en/api.html

The query API is defined here: https://docs.vespa.ai/en/query-api.html and detailed here: https://docs.vespa.ai/en/reference/query-api-reference.html

**Comment by anishka25** [comment]
Can you assign this to me , I want to work on this

**Comment by Yash-sudo-web** [comment]
Can you assign this to me, i would like to work on this

**Comment by HarshMN2345** [comment]
Can you assign this to me , I want to work on this

**Comment by VrajPatelGitHub** [comment]
@sid-swirl I would like to work on this issue please assign these to me.

**Comment by erikspears** [comment]
This PR was merged to our develop branch and will be part of our next release to main.  Thank you for the contribution!

Closing this Issue.
