### ISSUE TITLE
Integration with Github Codespaces

### ISSUE THREAD

**Issue by s-vamshi** [swirlai/swirl-search#703]
### The Problem
Setting up local dev env is time consuming and not everyone's pc meet minimum system requirements for setup.

### The Solution
That's where Github Codespaces comes into picture and helps us in configuring project on cloud without need of installing anything on local pc.
It would be helpful for users of Swirl to easily setup dev env without any hustle(Without even entering single command to run).

**Comment by erikspears** [comment]
This has been merged...closing the Issue.  Thanks @s-vamshi !
