### ISSUE TITLE
Adding Contributors Section to the Readme.md File 

### ISSUE THREAD

**Issue by mohitd404** [swirlai/swirl-search#710]
Adding a contributors section to the README.md file provides recognition, fosters community, and enhances project transparency and accountability.

Example:- 
![3](https://github.com/swirlai/swirl-search/assets/146939900/8d8bba3b-7a6f-45d4-8bcc-dbf5fab020f7)

@erikspears Kindly assign this Issue to me! Thank You !!

**Comment by erikspears** [comment]
Done!  @mohitd404 :)

**Comment by mohitd404** [comment]
@erikspears I have made the changes Kindly review it ! Thank you!

**Comment by erikspears** [comment]
Nice idea!  One question before we merge the PR:  does this solution create a dynamic list (image, really) of contributors that will change as new folks have code merged, etc.?  Or is it a static output that requires some manual intervention to update?

Thanks,
--Erik

**Comment by mohitd404** [comment]
> @mohitd404 , Nice idea! One question before we merge the PR: does this solution create a dynamic list (image, really) of contributors that will change as new folks have code merged, etc.? Or is it a static output that requires some manual intervention to update?
> 
> Thanks, --Erik
It creates a Static image of the contributors it does not update as new contributions are adds to the repo! However, I can also create a Dynamic Contributors section which will update with the new contributions, but it will need to maintain ".all-contributorsrc" file for every new contributor to the maintainer manually it is not possible to make it dynamic.

**Comment by erikspears** [comment]
@mohitd404 ,

OK, thanks for that.  I think a static image doesn't bode well for future maintenance, to be honest 😆 
Would you mind PR-ing the more dynamic approach, with the understand that some manual upkeep is still required?  You could either close your current PR and open a fresh one, or update the one you have.  Whichever makes more sense to you is just fine.

Thanks,
--Erik

**Comment by mohitd404** [comment]
> @mohitd404 ,
> 
> OK, thanks for that. I think a static image doesn't bode well for future maintenance, to be honest 😆 Would you mind PR-ing the more dynamic approach, with the understand that some manual upkeep is still required? You could either close your current PR and open a fresh one, or update the one you have. Whichever makes more sense to you is just fine.
> 
> Thanks, --Erik

Okay @erikspears I'll implement it in dynamic approach !
