### ISSUE TITLE
Button should be cursor pointer and add link to arrow

### ISSUE THREAD

**Issue by AnshuPathak-88825** [swirlai/swirl-search#711]
![Screenshot from 2023-10-10 06-03-48](https://github.com/swirlai/swirl-search/assets/78332454/2062e4f9-10d7-4823-b3c5-3bbf401a2e5b)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by dnicodemus** [comment]
Please provide screen shots of what you're planning, it's not clear from your description.

**Comment by AnshuPathak-88825** [comment]
Working on it

**Comment by erikspears** [comment]
We have removed the Hacktoberfest banner from the repo's Readme file, as that event is now over.  Closing this Issue.
