### ISSUE TITLE
Add installation and Getting Started guide in readme

### ISSUE THREAD

**Issue by AnshuPathak-88825** [swirlai/swirl-search#712]

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by srbhr** [comment]
I think our readme already has a getting started and installation guide.

**Comment by AnshuPathak-88825** [comment]
Working on it

**Comment by AnshuPathak-88825** [comment]
pr created now you can review pr from github repo https://github.com/AnshuPathak-88825/swirl-search/tree/issue712 branch issue712

**Comment by erikspears** [comment]
Thank you for the contribution, but that PR has been closed; it turns out we cannot take it at this time.
