### ISSUE TITLE
Integration with Gitpod

### ISSUE THREAD

**Issue by s-vamshi** [swirlai/swirl-search#714]
The Problem
Setting up local dev env is time consuming and not everyone's pc meet minimum system requirements for setup.

The Solution
That's where Gitpod comes into picture and helps us in configuring project on cloud without need of installing anything on local pc.
It would be helpful for users of Swirl to easily setup dev env without any hustle(Without even entering single command to run).

**Comment by sid-swirl** [comment]
Thank you! Reviewing now

**Comment by sid-swirl** [comment]
Completed! Thank you @s-vamshi
