### ISSUE TITLE
SWIRL won't highlight terms that have preceding or trailing quotes in the query

### ISSUE THREAD

**Issue by erikspears** [swirlai/swirl-search#72]
From the v. 1.7 Release Notes:

> For example `'hello` or `'hello'`. These may be quite acceptable to search engines as phrase searches. This will be fixed in a future release.

This is also true of double quotes; searching returns expected results but SWIRL doesn't highlight the matching word if the query is passed with quotation marks in front, for example.

**Comment by sidprobstein** [comment]
Resolved in 1.8

**Comment by erikspears** [comment]
Checking this in the latest 1.8 (pulled a few minutes ago), and I don't _think_ it's fixed.

Search term:  `'hello`
None of the top 10 results returned had any highlighting in them (no occurrence of the `*` character in the page).
Screen grab of the top 2 hits; matching term visible in both (title and body) but no highlighting from Swirl:
![Issue 72 - leading single quote results](https://user-images.githubusercontent.com/98238295/212753742-3b8a2264-d2dd-4fbe-99cf-6000a9b2ffb2.png)

Search term:  `"world"`
None of the top 10 results returned had any highlighting in them (no occurrence of the `*` character in the page).
Screen grab of the top 2 hits; matching term visible in both (title and body) but no highlighting from Swirl:
![Issue 72 - double quote results](https://user-images.githubusercontent.com/98238295/212753794-ccaef8a7-124e-4139-8f0c-0b7ffd6a294d.png)

@sidprobstein , wdyt?  Has the expected behavior around this Issue changed in 1.8?

**Comment by erikspears** [comment]
Additional example that may help clarify (or confuse) things 😆 

Search term:  `'blogger'`
We DO see one instance of highlighting here, and it includes the single quotes.  See the 1st result (with 
![Issue 72 - single quote results match](https://user-images.githubusercontent.com/98238295/212754666-4b853ab6-a0b5-4659-9267-3192853d8e6c.png)
2nd hit included too):

CC:  @sidprobstein

**Comment by ryandeisma** [comment]
Branch 1.11, 1.10.1, and main, do not see any change in above commented examples of different quote permutations of 'hello' or 'blogger'. However, double quotes appears to be significantly improved and has highlighting applied. Fix remaining is a solution to single quotes for highlighting.
