### ISSUE TITLE
Connector: qdrant

### ISSUE THREAD

**Issue by sid-swirl** [swirlai/swirl-search#721]
Qdrant is a vector database & vector similarity search engine. It deploys as an API service providing search for the nearest high-dimensional vectors. With Qdrant, embeddings or neural network encoders can be turned into full-fledged applications for matching, searching, recommending, and much more!

API documentation is here: https://qdrant.github.io/qdrant/redoc/index.html

**Comment by akarsh-jain-790** [comment]
@sid-swirl I would like to work on this issue, can you assign it to me?

**Comment by neelshah2409** [comment]
Hey @sid-swirl I  would like to go for this issue

**Comment by sidprobstein** [comment]
Accepted PR
