### ISSUE TITLE
Table of Content 

### ISSUE THREAD

**Issue by Durgesh4993** [swirlai/swirl-search#731]
Can i create the table of content (index) which helps to user read the documentation

Example:

![image](https://github.com/swirlai/swirl-search/assets/98798977/97db55b3-a78c-40f3-a6c3-97aadbf69f2e)

**Comment by erikspears** [comment]
Hi @Durgesh4993 ,

Where do you see this ToC landing?  Is it the repo's Readme file, or elsewhere?  Do you envision it replacing content that already exists, and if so, which content?

Thanks,
--Erik

**Comment by Durgesh4993** [comment]
No i don't want change any documentation, I just want to add ToC in readme file which helps to find documantation easily

**Comment by Durgesh4993** [comment]
@erikspears Can i do this task

**Comment by erikspears** [comment]
@Durgesh4993 , yes of course, open a PR and the team will review.  Thanks for the clarification as well!

**Comment by erikspears** [comment]
Our product documentation now lives here ([https://docs.swirl.today/](https://docs.swirl.today/)), and includes both persistent navigation between the guides, a table of contents for each individual guide, and also a nice find in page feature.

Thank you for the suggestion, we're closing this Issue out now.
