### ISSUE TITLE
Improve Swirl Pricing card header alignment

### ISSUE THREAD

**Issue by ronisarkarexe** [swirlai/swirl-search#733]
Description:
Improve pricing card header alignment and section padding, it will look better.

![pricing](https://github.com/swirlai/swirl-search/assets/76697055/aa41020f-7578-4f59-86ef-5a751d53cb4f)

**Comment by ronisarkarexe** [comment]
Could you please assign me to this issue?

**Comment by ronisarkarexe** [comment]
> Hi @ronisarkarexe , This appears to be a suggested correction to our public webiste, swirl.today, and not our code repo on GitHub. Can you please confirm that's what you are intending?
> 
> If so, Saurabh R., please work with Adam on the team to assess the suggested change?
> 
> Thanks, --Erik

While browsing the swirl-search repository, I came across an issue with the cards on swirl.today, a public website. Upon visiting the live URL, I noticed the issue and wanted to contribute to the project by reporting it. I hope this information is helpful to you.

**Comment by erikspears** [comment]
Hi @ronisarkarexe, 
Our public website isn't part of our repo, but we appreciated you pointing this out!  We've passed it on to the folks who maintain the site.  Adjustments may appear in future versions of the website.  Closing this out.
