### ISSUE TITLE
Improve UI Features of Swirl

### ISSUE THREAD

**Issue by ronisarkarexe** [swirlai/swirl-search#734]
Description: 
I suggest adjusting the text alignment for better readability. 

![featureImprove](https://github.com/swirlai/swirl-search/assets/76697055/40ab17cd-a8bd-4785-acb2-c881eec2b157)

**Comment by srbhr** [comment]
This is from the Swirl's website. Swirl's UI has nothing to do with this.

**Comment by erikspears** [comment]
Yes, this looks to be feedback for the public website, swirl.today.  Is that correct @ronisarkarexe ?

If so, @srbhr , please work with Adam to assess the level of effort to make this adjustment.

Thanks,
--Erik

**Comment by ronisarkarexe** [comment]
> Yes, this looks to be feedback for the public website, swirl.today. Is that correct @ronisarkarexe ?
> 
> If so, @srbhr , please work with Adam to assess the level of effort to make this adjustment.
> 
> Thanks, --Erik

yes, it's from swirl.today

**Comment by ronisarkarexe** [comment]
> > Yes, this looks to be feedback for the public website, swirl.today. Is that correct @ronisarkarexe ?
> > If so, @srbhr , please work with Adam to assess the level of effort to make this adjustment.
> > Thanks, --Erik
> 
> yes, it's from swirl.today

https://swirl.today/product/

**Comment by srbhr** [comment]
Yes, it seems like the current theme that we are using has this "feature"

**Comment by erikspears** [comment]
Hi again @ronisarkarexe,
As with the other Issue, our public website isn't part of our repo, but we appreciated you pointing this out! We've passed it on to the folks who maintain the site. Adjustments may appear in future versions of the website. Closing this out.
