### ISSUE TITLE
Typos in the Docs

### ISSUE THREAD

**Issue by biplobsd** [swirlai/swirl-search#737]
I found many of typos. Here is the list of spell errors -

https://github.com/swirlai/swirl-search/blob/main/README.md
conenctor -> connector

https://github.com/swirlai/swirl-search/blob/main/SECURITY.md
breif -> brief 

https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start
instrutions -> instructions 
runnning -> runnning 
instrutions -> instructions 
runnning -> running 

https://github.com/swirlai/swirl-search/wiki/2.-User-Guide
occurances -> occurrences  
respository -> repository 
pre-loaded -> preloaded 
Artciles -> Articles
Metaseaerch -> Metasearch 
id's -> ids
identifes -> identifies 
identifes -> identifies 
udpated -> updated
mid-term -> midterm 
mutiple -> multiple 
Develper -> Developer 

https://github.com/swirlai/swirl-search/wiki/3.-Admin-Guide
adminstrators -> administrators 
Tranformations -> Transformation
theshold -> threshold 
verion -> version 
FDQN -> FQDN 
commmand -> command 
Deelete -> Delete 

https://github.com/swirlai/swirl-search/wiki/4.-M365-Guide
resultling -> resulting 
searchbox -> search box
distribtuion -> distribution 

https://github.com/swirlai/swirl-search/wiki/5.-Developer-Guide 
overriden -> overridden
asssign -> assign 

https://github.com/swirlai/swirl-search/wiki/6.-Developer-Reference
occured -> occurred 
availabe -> available 
verion -> version 
specifed -> specified 
specifed -> specified 
mappinging -> mapping in
udpated -> updated 
Connetor -> Connector 
commmand -> command 
elipsis -> ellipsis 

I also check in the docs directory md files. That typo still here. I want to work on the repository part. But in the wiki, I'm not sure how to fix with PR. Please check those words is error or not.

**Comment by erikspears** [comment]
Hi @biplobsd ,

You've caught us at an interesting moment. :)  We are literally in the midst of swiching from using GitHub's Wiki to using the docs/ directory to drive a GitHub Pages version of our documentation.  These catches are great, and I'll make sure they get fixed once the dust is settled on the GH Pages process, which is still WIP at the moment.

Many thanks,
--Erik

**Comment by nrhitik** [comment]
is this issue still up for contribution? if yes could you assign me this issue.

**Comment by erikspears** [comment]
Hi @nrhitik , you've caught us in a moment of transition with regard to the documentation.  We migrating away from the GitHub wiki to a GH Pages publishing method.  We're literaly in the midst of it.  And we have a few PRs plus this list of doc updates / typos to fix.  You could add to that, but nothting will change until we finish sorting them new publishing process.  After that, I'll take all the suggestions / corrections, and make sure they land in the new docs world.  :)

**Comment by erikspears** [comment]
OK, this is all set.  We had some other typo corrections submitted as PRs and then this list as well.  All the relevant corrections are no in the new Documentation structure that is in the repo (docs/) directory.  Welll be shutting down the wiki and publishing this new structure widely within the next few days.  Many thanks @biplobsd , closing this Issue out.

PS:  Did you eyeball of these or do you have a markdown spell-checker that you use/prefer?

**Comment by biplobsd** [comment]
@erikspears  I was reading aloud wiki from Edge browser. Then I listen to mispronounced word. Then I use Google Docs for highlighting all words and note down and finally create a pull request. But I forgot to check, @Akash190104  already open some pr.😊 Good to see all of the words now corrected.

**Comment by Akash190104** [comment]
@erikspears to answer your question, I actually use the Grammarly extension. The moment I try to edit any markdown file it highlights the typos which I verify after understanding what the document wants to say. It makes it a lot easier to find typos but in a lot of cases, the document makes perfect sense and there's no point in making the changes which Grammarly wants me to make.
Also, thanks @biplobsd for your comment.

**Comment by erikspears** [comment]
Interesting!  Thanks for the info, both of you.  It's always an interesting typo-challenge wrangling a lot of markdown.  😆
