### ISSUE TITLE
Can i add whole docker files into docker folder 

### ISSUE THREAD

**Issue by Durgesh4993** [swirlai/swirl-search#756]
![image](https://github.com/swirlai/swirl-search/assets/98798977/08ece0c1-525d-4aa9-b4db-891a0a4d937f)

**Comment by Durgesh4993** [comment]
@erikspears could you assign this task to me

**Comment by erikspears** [comment]
@Durgesh4993 assigned...what is it you want to accomplish with this task?  Just curious as to the benefits of your approach, if you could say something about that.  Thanks!

**Comment by Durgesh4993** [comment]
@erikspears Thank you, for giving me opportunity to do this task

**Comment by erikspears** [comment]
Closing this out.
