### ISSUE TITLE
Unresponsive Swirl Logo in Login Page

### ISSUE THREAD

**Issue by s-vamshi** [swirlai/swirl-search#761]
On login page:
1. When I inspect
2. Zoom in/out
3. Resize window
Swirl logo gets disappeared

OS - Windows 10

Browser - Chrome

[screen-capture (6).webm](https://github.com/swirlai/swirl-search/assets/62489114/ad94f829-1f00-46b1-b48c-fcf768851174)

**Comment by ShatilKhan** [comment]
Please assign me, I'll fix it up

**Comment by heysagnik** [comment]
PLease assign me

**Comment by srbhr** [comment]
Thanks, @s-vamshi, for pointing this out. The team will fix it up in the coming versions.

**Comment by erikspears** [comment]
In Release 3.0, out now, the Galaxy UI login page now handles window resizing more gracefully.
Thank you for letting us know!  Closing this Issue.
