### ISSUE TITLE
[Feature] : Custom Scroll Bar 

### ISSUE THREAD

**Issue by letscodedanish** [swirlai/swirl-search#785]
I would suggest a Custom scroll bar which suits well to the swirl website, which will eventually enhance the UI of the website.

Right now the scroll looks something like this:
![Screenshot (521)](https://github.com/swirlai/swirl-search/assets/112203113/0bcb473c-e98b-4619-91d3-cf267285a980)

I can fix this, and enhance the aesthetics of the website, please assign it to me.

**Comment by srbhr** [comment]
Hi @letscodedanish Thanks for raising an issue. The website is not open source, and we'll fix this in the coming versions of the website.

**Comment by letscodedanish** [comment]
@erikspears should i work on this?

**Comment by erikspears** [comment]
Hi @letscodedanish , please see Saurabh's comment just above.  Our website is not really part of the open-source project for Swirl on GitHub.  We do appreciate the suggestion, for sure, and we'll take a look next time we update the website.

--Erik

**Comment by erikspears** [comment]
Hi @letscodedanish ,
Our public website isn't part of our repo, but we appreciated you pointing this out! We've passed it on to the folks who maintain the site. Adjustments may appear in future versions of the website. Closing this out.
