### ISSUE TITLE
Improve Responsiveness for the Website

### ISSUE THREAD

**Issue by hanzalahwaheed** [swirlai/swirl-search#786]
![image](https://github.com/swirlai/swirl-search/assets/101456741/d5e1460d-f6ce-4ae8-bed0-8b289d301bf1)

- When opening the website on a Mobile, the information separating lines should've been in between in the "_Quickly find all your Information_" section, rather than on the side.
- The logos over here can have more bottom-padding for a better look.

![image](https://github.com/swirlai/swirl-search/assets/101456741/d922750e-7886-4639-add3-8062b8c97aea)

- Some padding can be given here as well in between the "_Learn More_" and "_Get in Touch_" buttons.

**Comment by akash0708** [comment]
Hello @hanzalahwaheed , I would love to work on this.

**Comment by hanzalahwaheed** [comment]
@akash0708 Yes, you can start if someone assigns it to you. I'm actually not a Maintainer.

**Comment by srbhr** [comment]
Thanks for creating an issue, @hanzalahwaheed and @akash0708. The website is not open source, and we will fix this in the coming versions of the website. May I know the width of the device that you're using? @hanzalahwaheed So that we can test it in the future versions of the website.

**Comment by hanzalahwaheed** [comment]
@srbhr I tested it on the Chrome Web tools' Pixel 5

**Comment by thevinitgupta** [comment]
You could also look at the following responsiveness issues :

![Screenshot_2023-10-16-16-20-08-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/swirlai/swirl-search/assets/65801700/7a574a6e-359d-4df8-a2cb-c2047e162419)

![Screenshot_2023-10-16-16-20-15-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/swirlai/swirl-search/assets/65801700/17b8b240-781e-4bbd-b0b6-2bf68b5acadf)
## For the following image, you could something like removing the sticky property where the user reaches the footer section
![Screenshot_2023-10-16-16-20-24-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/swirlai/swirl-search/assets/65801700/d4595fd2-068b-48ed-a732-81f6d9a1657e)

**Comment by erikspears** [comment]
Hi @hanzalahwaheed ,
Our public website isn't part of our repo, but we appreciated you pointing this out! We've passed it on to the folks who maintain the site. Adjustments may appear in future versions of the website. Closing this out.
