### ISSUE TITLE
Add Social Preview

### ISSUE THREAD

**Issue by Pedro-Ivo-Neves** [swirlai/swirl-search#798]
I think you could add a social preview for the repository be more appealing to more contributors.
Like the following image:

![image](https://github.com/swirlai/swirl-search/assets/83455817/ce1b7d0d-0810-4cfe-9323-4d5ffef7b1fb)

**Comment by erikspears** [comment]
Hi @Pedro-Ivo-Neves , we have a Social Preview image setup in the repo already.  We may at some point update it to another of our logos as well.  Thanks for asking about this though!  Closing this Issue now.
