### ISSUE TITLE
Fix Typos and Grammatical errors in Readme

### ISSUE THREAD

**Issue by singodiyashubham87** [swirlai/swirl-search#840]
**Describe the bug**
There are some typos and grammar errors in the README file which need to be corrected.

**To Reproduce**
I will rectify all the grammatical errors and typos.

**Expected behaviour**
Grammar should have to be correct.

**Screenshots**
For example, Here is written "Swirl is open source" but it should have to be "Swirl is an open source".
![image](https://github.com/swirlai/swirl-search/assets/93720428/b59a3b23-eea4-4fa3-8da3-be105e54d269)

Kindly assign this issue to me..

**Comment by erikspears** [comment]
Thank you for the contribution, but that PR has been closed; it turns out we cannot take it at this time.
