### ISSUE TITLE
Change color of social icons on hover 

### ISSUE THREAD

**Issue by singodiyashubham87** [swirlai/swirl-search#841]
**Describe the bug**
The colour of navbar items "Product" and "About" becomes blue when hovered but the social icons just scale up and does not change their color which is making the UI inconsistent

**To Reproduce**
Steps to reproduce the behaviour:
Alter the hover property of social icons and make the color on hover same as that of other 2 navbar elements.

**Expected behavior**
All navbar elements should have the same consistent color scheme on hover

**Screenshots**
![Screenshot from 2023-10-23 11-29-19](https://github.com/swirlai/swirl-search/assets/93720428/77e77c54-98bc-45be-9d34-3a39e0e6f7f3)
![Screenshot from 2023-10-23 11-29-10](https://github.com/swirlai/swirl-search/assets/93720428/770a3ca0-d10b-40ba-86a9-c9df382618f4)
![Screenshot from 2023-10-23 11-29-05](https://github.com/swirlai/swirl-search/assets/93720428/e4826216-509e-4f62-bc33-36897e1a1296)

**For UI Issues (please complete the following information):**
 - OS: Kali Linux
 - Browser + Version [Brave 116.0]

Kindly assign this issue to me

**Comment by erikspears** [comment]
Hi @singodiyashubham87 ,
Just to confirm, our public website isn't part of our repo, but we appreciated you pointing this out! We've passed it on to the folks who maintain the site. Adjustments may appear in future versions of the website. Closing this out.
