### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [swirlai/swirl-search#899]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/swirlai/swirl-search/assets/147402107/ba1e7f5f-c144-43ea-8541-6bcc9e429856)

**Comment by Kalyanimhala** [comment]
@erikspears  Kindly assign me this #899 issue, I want to work on it. Thank You!!

**Comment by erikspears** [comment]
Hi @Kalyanimhala ,

Is this a dynamic solution for adding and managing contributors?  Or does it require manual maintenance periodically?

Thanks,
--Erik

**Comment by Kalyanimhala** [comment]
Yeah, This will encourage the other contributors to contribute in the Repo!
so its a generalized solution to add  contributors in the readme.md file.
Thanks!!

**Comment by erikspears** [comment]
Thank you for the contribution, but that PR has been closed; it turns out we cannot take it at this time.
