### ISSUE TITLE
Docker searches on MacOS taking ~2 minutes to complete (Swirl 1.8)

### ISSUE THREAD

**Issue by erikspears** [swirlai/swirl-search#91]
In doing some basic testing of Swirl 1.8, it's clear the Docker-ized version is taking longer to return results than before.  Running on a MacBook Pro with an M1 chip, fwiw.

With only the 3 basic PSE SearchProviders plus newsdata.io, here are some search times from 1.8 running in Docker:
```
        "date_created": "2023-01-15T14:33:58.591587-05:00",
        "date_updated": "2023-01-15T14:35:49.267929-05:00",
```

```
        "date_created": "2023-01-15T14:00:27.947574-05:00",
        "date_updated": "2023-01-15T14:02:14.049838-05:00",
```

```
        "date_created": "2023-01-15T13:43:42.819850-05:00",
        "date_updated": "2023-01-15T13:45:19.962150-05:00",
```

These are taken directly from the Search List page in v. 1.8 (http://localhost:8000/swirl/search/)

Not sure what can be done, but if searches take much longer, using Docker on this hardware becomes less and less tenable.  Tagging it as a question for now.  Might also be fodder for a Discussion?

**Comment by sidprobstein** [comment]
Wow

**Comment by sidprobstein** [comment]
Investigating

**Comment by erikspears** [comment]
It seems to be hanging out in this state for too long (in Docker) ... from the Search List page:
```
"status": "POST_RESULT_PROCESSING",
```

**Comment by erikspears** [comment]
Moderate improvement here with v. 1.8.1 Docker updates, but searches still take 1+ minutes with most of that time spent in the `POST_RESULT_PROCESSING` state.  Perhaps the `DedupeByFieldPostResultProcessor` is a suspect.

Otherwise, could be something unique to Docker on an M1 MacBook Pro.  Container is consistently showing this warning in Docker Desktop:
<img width="729" alt="Docker container warning" src="https://user-images.githubusercontent.com/98238295/213932288-835640c4-ed82-48b4-83e1-ce7cc4ec72cd.png">

Relevant Q&A online includes:
- https://stackoverflow.com/questions/70765522/docker-amd64-warning-on-apple-m1-computer
- https://enjoi.dev/posts/2021-07-23-docker-using-amd64-images-on-apple-m1/

@sidprobstein, perhaps we could try adjusting the image used for builds at DockerHub?  🤔

**Comment by erikspears** [comment]
Reassigning to @dnicodemus for a look-see.

**Comment by dnicodemus** [comment]
We have had good success w/ performance improvement and normalization for both AMD and ARM architectures, now we need to implement the multi-arch container build in the regular deployment work flow. Looking into this now.

Creation and build/push that works:

```
docker buildx create --name devBuilder --use --bootstrap
docker buildx build -t dnicoswirl/test:multi-latest --platform linux/amd64,linux/arm64 --push .

```

**Comment by dnicodemus** [comment]
Working on automating the above, getting close.

**Comment by erikspears** [comment]
@dhdnicodemus , this has been greatly improved with the changes to the Docker build process.  In-house testing on both M1 and M2 machines is very positive.  Are you comfortable closing this one out now?  
CC:  @sidprobstein

**Comment by erikspears** [comment]
Closing it out, performance is much improved!
